### PR TITLE
Remove bzip2 support on all platforms.

### PR DESCRIPTION
**Pull request by freylint**
Removes compression support from the `zip` dependency.
Discussion for this is in #12.

### CODE REVIEW

**Comment by hannobraun** [comment]
Thank you for the pull request, @freylint! I'll take a closer look on Monday. So far I'm noticing that the `deflate` feature is no longer enabled. Is that deliberate?

**Comment by freylint** [comment]
> `deflate` feature is no longer enabled. Is that deliberate?

My understanding is that `deflate` is another compression algorithm like bzip2.
I removed it as it doesn't appear to be being used, so there's no need for end users to compile it.

See: https://en.wikipedia.org/wiki/Deflate

**Comment by hannobraun** [comment]
Turns out DEFLATE actually is used!

This crate uses the default options for adding files to the zip archive:
https://github.com/hannobraun/3mf-rs/blob/f673127a8247926fc45e9162a0fa983c3a8acf2f/src/write.rs#L18

Which means DEFLATE, if the `deflate` feature is enabled:
https://github.com/zip-rs/zip/blob/bb230ef56adc13436d1fcdfaa489249d119c498f/src/write.rs#L116-L121

So this pull request just disables compression:
https://github.com/zip-rs/zip/blob/bb230ef56adc13436d1fcdfaa489249d119c498f/src/write.rs#L122-L127

I mean, that's not horrible, but I also see no reason to change the default. I think we should leave the `deflate` feature enabled.

**Review by hannobraun — APPROVED** [review]
Thank you, @freylint, looks good to me!

**Comment by hannobraun** [comment]
I will publish a new version on crates.io shortly.

**Pull request merged**
